# Generated by Django 6.1.1 on 2026-09-18 18:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authorizeduser_is_super_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'failure_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
