# Generated by Django 6.1.1 on 2026-09-15 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('question_text', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ANSWERED', 'Answered')], default='APPROVED', max_length=20)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stream_questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='International Retreat Live Stream', max_length=200)),
                ('youtube_url', models.CharField(default='https://www.youtube.com/watch?v=jfKfPfyJRdk', max_length=500)),
                ('youtube_video_id', models.CharField(default='jfKfPfyJRdk', max_length=50)),
                ('is_live', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stream_configs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
