# Generated by Django 6.1.1 on 2026-09-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamconfig',
            name='offline_image_url',
            field=models.TextField(default='https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80'),
        ),
        migrations.AddField(
            model_name='streamconfig',
            name='offline_message',
            field=models.CharField(default='The live broadcast is currently offline. Please stay tuned for the next session.', max_length=300),
        ),
    ]
