# Generated by Django 6.1.1 on 2026-09-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_app', '0002_streamconfig_offline_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamconfig',
            name='is_playback_mode',
            field=models.BooleanField(default=False),
        ),
    ]
