# Generated by Django 6.1.1 on 2026-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_app', '0003_streamconfig_is_playback_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamconfig',
            name='is_emergency_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
